### ISSUE TITLE
Missing ability for gara

### ISSUE THREAD

**Issue by zereth7** [cmd430/Warframe-EHP-Calculator#1]
like the title says, you're missing the "Splinter Storm" ability for gara, which has up to 90% damage reduction (to both shields and health). doesn't directly affect the health or armor values, but still clearly would affect your ehp.

easy enough to figure it out anyway since i can just take my ehp * 10. but would be nice to see it included

**Comment by cmd430** [comment]
Fixed, was a bug It was added but wasnt set to show up!
