### ISSUE TITLE
Coaction Drift doesn't work with Aerodynamic

### ISSUE THREAD

**Issue by GlitchMC** [cmd430/Warframe-EHP-Calculator#14]
Turning on Coaction Drift while having Aerodynamic as your Aura lowers the end result of EHP by about half.
So far, I can only choose to use a maxed Coaction Drift, as a result of my previously submitted issue regarding the GUI. But as an example, Ash with Aerodynamic is 2119 EHP, while turning on Coaction Drift lowers it to 1051.

**Comment by cmd430** [comment]
Thanks for the report this issue is fixed in the next version
