### ISSUE TITLE
Sentinels use modded values as base

### ISSUE THREAD

**Issue by GlitchMC** [cmd430/Warframe-EHP-Calculator#15]
Sentinels use modded values for Health/Shields/Armor instead of their base values.

For example, Carrier Prime has 150 Base Armor, 400 Base Health, and 100 Base Shields. When Modded with fully ranked mods, its values become 315 Armor, 1280 Health, and 375 Shields.

However, on the calculator, Carrier Prime's base stats are listed as 315 Armor, 1280 Health, and 375 Shields, and when you choose to add mods, it alters those values to be 480 Armor, 2160 health, and 650 Shields.

**Comment by cmd430** [comment]
I looked into it and can confirm this bug, I was accidentally adding rank multipliers to sentinels, This has been fixed in the latest update (76b1e3a5b92f5ec5d32121e444b041878c0d0b1f)

Thanks
