### ISSUE TITLE
Oberon's passive is not correctly applied?

### ISSUE THREAD

**Issue by JaneSmith** [cmd430/Warframe-EHP-Calculator#16]
Hello. As far as I can tell, the calculator is applying Oberon's passive to sentinels. The wiki states that it only applies to kubrows and kavats:

> Oberon is one with nature and gains the following perks:
> - Allied Kubrows and Kavats receive +25% Health, Shield and Armor links.
> - The player's Kubrow or Kavat receives 1 instant revive per mission.
>
> Khora's Venari and MOA Companions, despite sharing some characteristics with Kubrows and Kavats, do not receive these benefits.

I am also unsure if the bonus is being applied correctly. I can't say whether it's right or not. From looking at the code, it seems like you're adding 75 armor and 1.25x health and shields to the pet. From the wiki's description with the word "link" I would expect it to work like the Link Health/Armor/Shield mods?

**Comment by cmd430** [comment]
Thanks I’ll look into this tonight

**Comment by cmd430** [comment]
closed by https://github.com/cmd430/Warframe-EHP-Calculator/commit/8af13eb9e91755dcdc83dce8b042f59d1940c011
