### ISSUE TITLE
"0.6" Popup

### ISSUE THREAD

**Issue by GlitchMC** [cmd430/Warframe-EHP-Calculator#17]
When selecting Aerodynamic as your Aura, you get a popup that simply says "0.6", with an OK button. Sometimes it shows up again immediately after hitting OK.

**Comment by cmd430** [comment]
oops left over debug msg, thanks update should fix it!

closed by https://github.com/cmd430/Warframe-EHP-Calculator/commit/d0937c2668af689d8776d0519de11eb759c68556
