### ISSUE TITLE
Miscellaneous Fixes

### ISSUE THREAD

**Issue by GlitchMC** [cmd430/Warframe-EHP-Calculator#18]
I'm not sure that these both require their own thread, so I just decided to make this one.

1. Blocking is now 100% Damage Reduction for all weapons, so having a blocking damage reduction box is unnecessary.
2. Titania's Thorns now reduces all damage taken by half, instead of the currently selectable 25 (which I assume was meant to be for Tribute's weakening effect on enemies who had their soul stolen).

**Comment by cmd430** [comment]
Thanks, for these reports, been pretty busy so its hard to keep up with all the current changes!

closed by https://github.com/cmd430/Warframe-EHP-Calculator/commit/e0fef9acd7291d6d5bdfbc9ac9c9a088757cd0d8
