### ISSUE TITLE
Rhino's Iron Skin doesn't seem to use the extra armor from Health Conversion

### ISSUE THREAD

**Issue by HK47196** [cmd430/Warframe-EHP-Calculator#2]
Issue title. Wiki implies they work together, and the ability info screen ingame definitely shows a big absorb increase with health conversion pickups.

**Comment by cmd430** [comment]
It seems to be working fine on my end any chance you can do a step by step (with pics too if possible) on how you get this issue?

**Comment by cmd430** [comment]
Here is an Imgur Album https://imgur.com/a/O3vas7W showing it on my end (Note the EHP values)

**Comment by cmd430** [comment]
am closing this issue, if you can provide steps to reproduce i'll reopen
