### ISSUE TITLE
Airborne Mods + Airborne Damage

### ISSUE THREAD

**Issue by GlitchMC** [cmd430/Warframe-EHP-Calculator#21]
Base Inaros has 3581 EHP (side thing, isn't that supposed to be 3580?), and stacking Aerodynamic, Agility Drift, and Aviator would be a total airborne DR on health of 76%. 3581 / .24 = 16045
However, the app shows a total EHP of 9595, which is only about 60% DR (3851 / .4 = 9627).

Individually, each of these mods give the correct amount of DR, but when stacking them, it seems that they're being diminished, when they should all be additive with each other.

.

Additionally, I recently found out about a couple of things myself too:

The first thing is that shield's 25% DR (or more specifically, its 0.75x damage multiplier) stacks additively with airborne mods (and resistance mods such as Antitoxin). Which wouldn't really mean much, if it weren't for the fact that Airborne modded DR was capped to 90% shortly after Aerodynamic was introduced. Which means that if you have 65% airborne resistance mods while airborne, then you will already be hitting that cap with your shields, and additionally airborne DR will not contribute to EHP for shields.

Secondly, and related to this, is that Adaptation counts for this. Meaning, that while you're grounded, your shields have their damage reduced by both the damage modifier of 0.75x, as well as Adaptations stacked 0.1x, for a total of 0.075x damage taken. However, once you're airborne, the 90% cap comes back into play, and you start taking 0.1x damage instead of 0.075x to your shields.

It may be rather complex to try to implement such mechanics into your app (my initial thoughts were to assume that if an airborne mod is selected, that they are airborne and subject to the 0.1x floor for damage taken), but I believe it would be rather important for a frame such as Titania, who can reach 89% airborne DR to shields simply with Aerodynamic and Aviator, so Agility Drift and Adaptation would be pretty much pointless, as they would only increase your DR to 90%.
From my testing, it seems that the 90% cap is only imposed for mods, as Ability DR stacks with modded DR as expected.

Details regarding the airborne mechanics are discussed [in this thread](https://www.reddit.com/r/Warframe/comments/fjrd0j/so_how_does_this_work_now_airborne_damage/fkpaa1e/).

**Comment by cmd430** [comment]
I've added a toggle under Special Effects (Airborne) to toggle state between on ground or in air, i've also corrected the DR to be additive, im getting 3 EHP different to you for Inaros but its likely from rounding, some numbers are slightly different under the hood than what is displayed (thanks decimals) so it should be correct now

closed by https://github.com/cmd430/Warframe-EHP-Calculator/commit/6c10b01c90ff8ff4705dd36af1ca0dc49021c88c

**Comment by GlitchMC** [comment]
Thanks for the fixes, and thanks for this project as a whole, it's really appreciated!
