### ISSUE TITLE
Umbra mods / Umbra Excal

### ISSUE THREAD

**Issue by Jigoogly** [cmd430/Warframe-EHP-Calculator#3]
just curious about the ETA

also exalted weapons.

**Comment by cmd430** [comment]
I’ll get it done this month I’m just way for work so not at my computer for long to be able to make the changes but it’ll get done :)

**Comment by cmd430** [comment]
As for exalted weapons they don’t affect the EHP so they won’t be added

**Comment by JaneSmith** [comment]
Exalted Blade gives a 60% damage reduction from the front at all times. You don't consider that affecting EHP?

**Comment by cmd430** [comment]
No I do just didn’t realise it did that my mistake, I’ll add it in the next update

**Comment by JaneSmith** [comment]
This is marked as completed, but there doesn't seem to be any new release since 2017. Any idea when a release will be made?

**Comment by cmd430** [comment]
I stopped doing the “release” thing on github, just download the exe from [the git repo](https://github.com/cmd430/Warframe-EHP-Calculator/blob/master/Warframe%20EHP%20Calculator%20v2/bin/Debug/Warframe%20EHP%20Calculator%20v2.exe) and then any new updates it will prompt you to download the update (with a link)
