### ISSUE TITLE
Efficiency for QuickThinking

### ISSUE THREAD

**Issue by NightRaivyn** [cmd430/Warframe-EHP-Calculator#4]
Hi i like the calculator atm but could you add in the efficiency calculation effect for QuickThinking?

**Comment by cmd430** [comment]
im sorry im not sure what you mean ?

Edit: if you mean the "At 240%" efficiency from the mod card (at max rank) thats already taken care of
[see this line of code](https://github.com/cmd430/Warframe-EHP-Calculator/blob/master/Warframe%20EHP%20Calculator%20v2/Form_Main.vb#L1018)

It takes the HP then adds the Energy value to it, The efficiency just part is handled by multiplying the energy by the mod rank efficiecy (so at max rank 2.4x) before adding that value to Health

**Comment by NightRaivyn** [comment]
I mean by building efficiency on your warframe to improve quickthinkings effect up to +75% and including the negatives with Blind Rage

**Comment by cmd430** [comment]
warframe power efficiency does not affect quickthinking
