### ISSUE TITLE
Wrong result with armor mods

### ISSUE THREAD

**Issue by Mister-Arkse** [cmd430/Warframe-EHP-Calculator#5]
When I use armor mods (Steel Fiber, Gladiator Aegis or Armored Agility) the result is wrong.
An unranked Steel Fiber gives +10% armor, on Inaros with 200 base armor I should get 220 not 227.

![warframe ehp calculator v2_2018-08-24_07-49-03](https://user-images.githubusercontent.com/16281589/44567374-6c4e9600-a772-11e8-925a-83f40fd09443.png)
![warframe ehp calculator v2_2018-08-24_07-50-36](https://user-images.githubusercontent.com/16281589/44567380-6f498680-a772-11e8-828a-0e1b516eeae6.png)
Don't mind the weirds colors, I'm using high constrast mode.

**Comment by cmd430** [comment]
I have fixed this and pushed an update
