### ISSUE TITLE
Suggestion for maintainability

### ISSUE THREAD

**Issue by Almagnus1** [cmd430/Warframe-EHP-Calculator#7]
Having recently tracked down a bug with Mag's vanilla HP at level 30, I would strongly encourage you to consider doing the following:

1. Create XML (or JSON) that would contain all of the warframes and their stats, for example:
```<warframes>
  <Excalibur>
    <base armor="225" health="100" shield="100" />
    <prime armor="300" health="100" shield="100" />
    <umbra armor="300" health="100" shield="100" />
</warframes>
```
From there you would need to use https://docs.microsoft.com/en-us/dotnet/standard/data/xml/xml-processing-options , specifically with classes to allow you to serialize the code into a warframe class, and then read from the class   The advantage to this is being able to quickly add a warframe (add it to the XML fragment, compile, done) rather than having to hunt down the appropriate line in combo box arrays.

Also using a Dictionary https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=netframework-4.7.2 to store the parsed XML would be ideal, as that will allow you to either assign Dictionary.Keys as the combobox list, or massage that into the correct data structure to use there.

2. Separate out your math and calculations from the UI code.  Code files that are hitting 3000 lines of code (or longer) are too long (with the exception of the UI autogenerated files) and this makes trying to track down bugs difficult.  Using classes with the UI will help break apart code into smaller, more manageable chunks.

3. Don't use static values for the level 30 health, shield, and armor values unless they are different from what the other warframes are doing.  The bug I found could have been avoided by just using math instead of trying to precalc everything.

**Comment by cmd430** [comment]
yeah im well aware of the issues, this started as a project for me and some clanies to use and was never really intended to be made public so i just threw it together.

I've wanted to go through and make it less shit for quite some time but I never seem to have enough time to go through and make it not shit haha, but in saying that I did just start a complete rewrite recently and im slowly chipping away at it when i can find the time :)

**Comment by cmd430** [comment]
#11 fixes this
