### ISSUE TITLE
Unairu - Stone Skin

### ISSUE THREAD

**Issue by Dimuscul** [cmd430/Warframe-EHP-Calculator#8]
Stone Skin applies as Base Armor (max rank of 60) but the calculator applies it an after all calculations (and as 80).

**Comment by cmd430** [comment]
... sorry I’m away for work so I rushed that release out just as I was leaving, im back again in a couple days so I’ll get it fixed up then, thanks for letting me know!

**Comment by cmd430** [comment]
Before i push this change could you please help me confirm Stoneskin is indeed adding base armor (im getting conflicing reports and i cant test it myself)

Could you please provide me with the following:
An in mission Screenshot of
* A Warframe with Stoneskin active with no mods
* A (the same) Warframe with Stoneskin disabled and with no mods 
* A (the same) Warframe with Stoneskin active with only steelfiber (and please specificy the rank of the steelfiber)
* A (the same) Warframe with Stoneskin disabled with only steelfiber (and please specificy the rank of the steelfiber)

Thanks!


Edit: im a dummy you cant see armor in values in mission :/

**Comment by cmd430** [comment]
So far 90% of the information i can find is showing that the armor is added after mods, i have corrected the armor amount added but am leaving it as a bonus after mods until i can be shown conclusivly otherwise.

update is out.
