### ISSUE TITLE
Could you consider making all mods maxed by default?

### ISSUE THREAD

**Issue by JaneSmith** [cmd430/Warframe-EHP-Calculator#9]
99% of the time, people are going to be using max rank mods in their builds. Unfortunately, Warframe EHP Calculator starts off with most mods at rank 0, and Umbral mods at rank 5. This means that before I can play around with builds, I have to first manually change them all to max rank. This is time consuming, tedious work that I have to do every time I launch the application.

Could you consider changing this please? Thanks.

**Comment by cmd430** [comment]
I've added a toggle for this in the next version that will be released once Equinox Prime is released you can expect it around the 2nd-3rd of April

**Comment by cmd430** [comment]
update is out
